BEGIN;
TRUNCATE TABLE chat_messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE chat_sessions RESTART IDENTITY CASCADE;
TRUNCATE TABLE edges RESTART IDENTITY CASCADE;
TRUNCATE TABLE nodes RESTART IDENTITY CASCADE;
TRUNCATE TABLE workflows RESTART IDENTITY CASCADE;
TRUNCATE TABLE chatbots RESTART IDENTITY CASCADE;
COMMIT;
